#!/bin/bash

# Environment Setup Script for Chat Handler Edge Function
# This script helps configure environment variables for deployment

set -e

echo "=========================================="
echo "小鳄鱼助手 - 环境配置向导"
echo "Chat Handler Environment Setup"
echo "=========================================="
echo ""

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to prompt for input
prompt_input() {
    local prompt_text=$1
    local var_name=$2
    local default_value=$3
    
    if [ -n "$default_value" ]; then
        read -p "$prompt_text [$default_value]: " input_value
        input_value=${input_value:-$default_value}
    else
        read -p "$prompt_text: " input_value
    fi
    
    eval "$var_name='$input_value'"
}

# Function to validate URL
validate_url() {
    local url=$1
    if [[ $url =~ ^https?:// ]]; then
        return 0
    else
        return 1
    fi
}

echo "请选择配置方式 (Choose configuration method):"
echo "1) 本地开发环境 (Local Development)"
echo "2) 生产环境 (Production via Supabase CLI)"
echo ""
read -p "选择 (1 or 2): " config_choice

case $config_choice in
    1)
        echo ""
        echo "${GREEN}配置本地开发环境...${NC}"
        echo ""
        
        # Supabase URL
        prompt_input "Supabase URL" SUPABASE_URL "https://your-project-ref.supabase.co"
        
        while ! validate_url "$SUPABASE_URL"; do
            echo "${RED}错误: URL 格式不正确，必须以 http:// 或 https:// 开头${NC}"
            prompt_input "Supabase URL" SUPABASE_URL "https://your-project-ref.supabase.co"
        done
        
        # Supabase Service Role Key
        prompt_input "Supabase Service Role Key" SUPABASE_SERVICE_ROLE_KEY
        
        # N8N Webhook URL
        prompt_input "N8N Webhook URL" N8N_WEBHOOK_URL "http://localhost:5678/webhook/croco-chat"
        
        while ! validate_url "$N8N_WEBHOOK_URL"; do
            echo "${RED}错误: URL 格式不正确，必须以 http:// 或 https:// 开头${NC}"
            prompt_input "N8N Webhook URL" N8N_WEBHOOK_URL "http://localhost:5678/webhook/croco-chat"
        done
        
        # Environment
        ENVIRONMENT="development"
        
        # Create .env.local file
        ENV_FILE="supabase/functions/chat-handler/.env.local"
        
        cat > "$ENV_FILE" << EOF
# Local Development Environment Variables
# Generated by setup-env.sh on $(date)

# Supabase Configuration
SUPABASE_URL=$SUPABASE_URL
SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY

# N8N Webhook Configuration
N8N_WEBHOOK_URL=$N8N_WEBHOOK_URL

# Environment
ENVIRONMENT=$ENVIRONMENT
EOF
        
        echo ""
        echo "${GREEN}✓ 本地环境配置已保存到: $ENV_FILE${NC}"
        echo ""
        echo "${YELLOW}提示:${NC}"
        echo "- 请确保 .env.local 文件不要提交到版本控制"
        echo "- 使用 'supabase functions serve' 启动本地开发服务器"
        echo ""
        ;;
        
    2)
        echo ""
        echo "${GREEN}配置生产环境 (通过 Supabase CLI)...${NC}"
        echo ""
        
        # Check if Supabase CLI is installed
        if ! command -v supabase &> /dev/null; then
            echo "${RED}错误: Supabase CLI 未安装${NC}"
            echo "请先安装 Supabase CLI:"
            echo "  macOS: brew install supabase/tap/supabase"
            echo "  其他平台: https://supabase.com/docs/guides/cli"
            exit 1
        fi
        
        # Supabase URL
        prompt_input "Supabase URL" SUPABASE_URL "https://your-project-ref.supabase.co"
        
        while ! validate_url "$SUPABASE_URL"; do
            echo "${RED}错误: URL 格式不正确，必须以 http:// 或 https:// 开头${NC}"
            prompt_input "Supabase URL" SUPABASE_URL "https://your-project-ref.supabase.co"
        done
        
        # Supabase Service Role Key
        prompt_input "Supabase Service Role Key" SUPABASE_SERVICE_ROLE_KEY
        
        # N8N Webhook URL
        prompt_input "N8N Webhook URL" N8N_WEBHOOK_URL "https://your-n8n-instance.com/webhook/croco-chat"
        
        while ! validate_url "$N8N_WEBHOOK_URL"; do
            echo "${RED}错误: URL 格式不正确，必须以 http:// 或 https:// 开头${NC}"
            prompt_input "N8N Webhook URL" N8N_WEBHOOK_URL "https://your-n8n-instance.com/webhook/croco-chat"
        done
        
        # Environment
        ENVIRONMENT="production"
        
        echo ""
        echo "${YELLOW}即将设置以下环境变量到 Supabase:${NC}"
        echo "  SUPABASE_URL=$SUPABASE_URL"
        echo "  SUPABASE_SERVICE_ROLE_KEY=***hidden***"
        echo "  N8N_WEBHOOK_URL=$N8N_WEBHOOK_URL"
        echo "  ENVIRONMENT=$ENVIRONMENT"
        echo ""
        read -p "确认设置? (y/n): " confirm
        
        if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
            echo "${RED}已取消${NC}"
            exit 0
        fi
        
        echo ""
        echo "设置环境变量..."
        
        # Set secrets using Supabase CLI
        supabase secrets set SUPABASE_URL="$SUPABASE_URL" || {
            echo "${RED}错误: 设置 SUPABASE_URL 失败${NC}"
            exit 1
        }
        
        supabase secrets set SUPABASE_SERVICE_ROLE_KEY="$SUPABASE_SERVICE_ROLE_KEY" || {
            echo "${RED}错误: 设置 SUPABASE_SERVICE_ROLE_KEY 失败${NC}"
            exit 1
        }
        
        supabase secrets set N8N_WEBHOOK_URL="$N8N_WEBHOOK_URL" || {
            echo "${RED}错误: 设置 N8N_WEBHOOK_URL 失败${NC}"
            exit 1
        }
        
        supabase secrets set ENVIRONMENT="$ENVIRONMENT" || {
            echo "${RED}错误: 设置 ENVIRONMENT 失败${NC}"
            exit 1
        }
        
        echo ""
        echo "${GREEN}✓ 环境变量已成功设置到 Supabase${NC}"
        echo ""
        echo "${YELLOW}下一步:${NC}"
        echo "1. 运行 'supabase functions deploy chat-handler' 部署函数"
        echo "2. 运行 'supabase secrets list' 验证环境变量"
        echo ""
        ;;
        
    *)
        echo "${RED}无效选择${NC}"
        exit 1
        ;;
esac

echo "=========================================="
echo "配置完成!"
echo "=========================================="
