-- Migration: Create user_generated_images table for guided image generation feature
-- This table stores images generated by users through the AI-guided creation process
-- 
-- Subtask 1.1: Create table structure with indexes and constraints
-- Subtask 1.2: Enable Supabase Realtime
-- Subtask 1.3: Configure RLS policies

-- ============================================================================
-- Subtask 1.1: Create user_generated_images table
-- ============================================================================

-- Create the user_generated_images table
CREATE TABLE IF NOT EXISTS public.user_generated_images (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  character_id uuid NOT NULL,
  conversation_id uuid NOT NULL,
  image_url text NOT NULL,
  thumbnail_url text,
  prompt text NOT NULL,
  style text NOT NULL,
  emotion text NOT NULL,
  user_description text NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  is_favorite boolean DEFAULT false,
  is_deleted boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT user_generated_images_pkey PRIMARY KEY (id),
  CONSTRAINT user_generated_images_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE,
  CONSTRAINT user_generated_images_character_id_fkey FOREIGN KEY (character_id) REFERENCES public.characters(id) ON DELETE CASCADE,
  CONSTRAINT user_generated_images_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id) ON DELETE CASCADE
);

-- Create indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_user_images_user_id ON public.user_generated_images(user_id);
CREATE INDEX IF NOT EXISTS idx_user_images_conversation ON public.user_generated_images(conversation_id);
CREATE INDEX IF NOT EXISTS idx_user_images_created_at ON public.user_generated_images(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_images_not_deleted ON public.user_generated_images(user_id, is_deleted) WHERE is_deleted = false;
CREATE INDEX IF NOT EXISTS idx_user_images_favorites ON public.user_generated_images(user_id, is_favorite) WHERE is_favorite = true AND is_deleted = false;

-- Add comment to table
COMMENT ON TABLE public.user_generated_images IS 'Stores AI-generated images created through guided conversation flow';

-- Add comments to important columns
COMMENT ON COLUMN public.user_generated_images.prompt IS 'Complete prompt used for image generation API';
COMMENT ON COLUMN public.user_generated_images.style IS 'Selected style preset (storybook, pixel, anime, scifi)';
COMMENT ON COLUMN public.user_generated_images.emotion IS 'Selected emotion preset (warm, mysterious, playful, calm)';
COMMENT ON COLUMN public.user_generated_images.user_description IS 'Original user description/theme';
COMMENT ON COLUMN public.user_generated_images.metadata IS 'Additional metadata (model, generation_time, api_provider, etc.)';
COMMENT ON COLUMN public.user_generated_images.is_deleted IS 'Soft delete flag - deleted images are hidden but not removed';

-- ============================================================================
-- Subtask 1.2: Enable Supabase Realtime
-- ============================================================================

-- Add table to Realtime publication for real-time notifications
ALTER PUBLICATION supabase_realtime ADD TABLE public.user_generated_images;

-- ============================================================================
-- Subtask 1.3: Configure RLS (Row Level Security) policies
-- ============================================================================

-- Enable RLS on the table
ALTER TABLE public.user_generated_images ENABLE ROW LEVEL SECURITY;

-- Policy 1: Users can view their own images
-- Validates: Requirements 12.1, 12.2
CREATE POLICY "Users can view their own images"
  ON public.user_generated_images
  FOR SELECT
  USING (auth.uid() = (SELECT auth_id FROM public.users WHERE id = user_id));

-- Policy 2: Users can insert their own images
-- Validates: Requirements 12.1
CREATE POLICY "Users can insert their own images"
  ON public.user_generated_images
  FOR INSERT
  WITH CHECK (auth.uid() = (SELECT auth_id FROM public.users WHERE id = user_id));

-- Policy 3: Users can update their own images (for favorite/delete operations)
-- Validates: Requirements 12.1, 12.2
CREATE POLICY "Users can update their own images"
  ON public.user_generated_images
  FOR UPDATE
  USING (auth.uid() = (SELECT auth_id FROM public.users WHERE id = user_id))
  WITH CHECK (auth.uid() = (SELECT auth_id FROM public.users WHERE id = user_id));

-- Policy 4: Service role can perform all operations (for N8N workflow)
CREATE POLICY "Service role has full access"
  ON public.user_generated_images
  FOR ALL
  USING (auth.jwt()->>'role' = 'service_role')
  WITH CHECK (auth.jwt()->>'role' = 'service_role');
